### ISSUE TITLE
Could not open library 'libcurl

### ISSUE THREAD

**Issue by FabulouSebas** [expo/expo-server-sdk-ruby#16]
Hello!
I have been trying to install the gem and i'm getting this stack trace : 

*rails aborted!
LoadError: Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so.4': libcurl.so.4: cannot open shared object file: No such file or directory
/usr/local/bundle/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib'
/usr/local/bundle/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `map'
/usr/local/bundle/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `<module:Curl>'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon/curl.rb:8:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/ethon-0.11.0/lib/ethon.rb:15:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `require'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
/usr/local/bundle/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
/var/www/docker/config/application.rb:9:in `<top (required)>'
/var/www/docker/Rakefile:4:in `require_relative'
/var/www/docker/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:12:in `block in run_rake_task'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/var/www/docker/bin/rails:9:in `require'
/var/www/docker/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/usr/local/bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/var/www/docker/bin/spring:14:in `require'
/var/www/docker/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'*

Would someone know which gem i am missing?

**Comment by elaco** [comment]
Maybe you don't have libcurl installed in your docker container.
Add `RUN apt-get install libcurl4-openssl-dev` in your dockerfile

**Comment by pablonahuelgomez** [comment]
@FabulouSebas hi, as @elaco says above, you need to install `libcurl` in your system. I'm closing this one in favor of that solution.
