### ISSUE TITLE
NameError: uninitialized constant Exponent

### ISSUE THREAD

**Issue by davidray** [expo/expo-server-sdk-ruby#31]
I've installed the gem in my rails app and this code:

client = Exponent::Push::Client.new

results in NameError: uninitialized constant Exponent.

If I try to require it, I get this error:

LoadError: cannot load such file -- exponent-server-sdk

It's possible I'm doing something stupid here. Any help will be appreciated.

**Comment by davidray** [comment]
I don't know what caused this, but I rebooted my computer and it went away.

**Comment by fabiobarboza7** [comment]
> I don't know what caused this, but I rebooted my computer and it went away.

It's just needed to restart the server to allow ./config initializers be loaded again.
